# Generated by Django 5.0.1 on 2024-01-05 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pptx', 'docx', 'xlsx'])]),
        ),
    ]
